Repository TogetherOS/cicada, pull requests merged in 2018-10, with the labels that each got.

#11 Dev 1.0.3/dynamic proxy
  README-ZH.md
  README.md
  cicada-core/pom.xml
  cicada-core/src/main/java/top/crossoverjie/cicada/server/CicadaServer.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/action/WorkAction.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/action/req/CicadaHttpRequest.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/action/req/CicadaRequest.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/action/res/CicadaHttpResponse.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/action/res/CicadaResponse.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/bootstrap/NettyBootStrap.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/constant/CicadaConstant.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/context/CicadaContext.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/handle/HttpDispatcher.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/init/CicadaInitializer.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/model/Msg.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/thread/ThreadLocalHolder.java
  cicada-example/pom.xml
  cicada-example/src/main/java/top/crossoverjie/cicada/example/action/DemoAction.java
  cicada-example/src/main/java/top/crossoverjie/cicada/example/action/TextAction.java
  cicada-example/src/main/java/top/crossoverjie/cicada/example/res/DemoResVO.java
  pom.xml
Labels: bug, new features

#21 Dev 1.0.4/responsibility
  cicada-core/pom.xml
  cicada-core/src/main/java/top/crossoverjie/cicada/server/annotation/Interceptor.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/handle/HttpDispatcher.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/intercept/AbstractCicadaInterceptorAdapter.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/intercept/CicadaInterceptor.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/intercept/InterceptProcess.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/intercept/OrderComparator.java
  cicada-core/src/main/java/top/crossoverjie/cicada/server/util/ClassScanner.java
  cicada-example/pom.xml
  cicada-example/src/main/java/top/crossoverjie/cicada/example/intercept/ExecuteTimeInterceptor.java
  cicada-example/src/main/java/top/crossoverjie/cicada/example/intercept/LoggerInterceptorAbstract.java
  pom.xml
Labels: new features

#24 #23 Modify getCicadaAction and getCicadaInterceptor.Enhance readabili…
  cicada-core/src/main/java/top/crossoverjie/cicada/server/util/ClassScanner.java
Labels: enhancement

#26 #23 Modify getCicadaAction and getCicadaInterceptor.Enhance readabili…
  cicada-core/src/main/java/top/crossoverjie/cicada/server/util/ClassScanner.java
Labels: enhancement
